spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobapptracker
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: com.jpettit.jobapplicationbackend.config.namingstrats.EnvironmentNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

tabledata:
  env: dev