# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Job Application Tracker Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out project sources
      uses: actions/checkout@v3
    - name: Set up Corretto JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17.0.6
        distribution: corretto
        cache: gradle
    - name: Setup Gradle and Test
      working-directory: backend/jobapplicationbackend
      run: ./gradlew build --no-daemon
