# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Job Application Tracker CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  buildtest_frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}  
        cache: 'npm'
        cache-dependency-path: 'frontend/jobapptrackerfrontend/package-lock.json'
    - name: Installing dependencies for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend 
      run: npm ci
    - name: Build project for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend
      run: npm run build --if-present
    - name: Run tests for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend
      run: npm test

  buildtest_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out project sources
      uses: actions/checkout@v3
    - name: Set up Corretto JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto
        cache: gradle
    - name: Build project and test
      working-directory: backend/jobapplicationbackend
      run: ./gradlew clean build
