# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TypeScript Frontend CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing dependencies for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend 
      run: npm ci
    - name: Build Project for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend
      run: npm run build --if-present
    - name: Run tests for Node.js ${{ matrix.node-version }}
      working-directory: frontend/jobapptrackerfrontend
      run: npm test
